# Generated by Django 6.0.1 on 2026-01-23 20:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('verb', models.CharField(choices=[('created', 'Created'), ('added', 'Added'), ('removed', 'Removed'), ('reordered', 'Reordered')], max_length=20)),
                ('entries', models.JSONField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='lists.list'))),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='lists.list')),
            ],
            options={
                'verbose_name_plural': 'list activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
