# Generated by Django 6.0.6 on 2026-08-08 21:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umamusume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('game_chara_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='umamusume.profile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('image_url', models.URLField(blank=True)),
                ('game_card_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to='umamusume.character')),
            ],
            options={
                'ordering': ['character__name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CareerRun',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_date', models.DateTimeField(db_index=True)),
                ('platform', models.CharField(choices=[('steam', 'Steam'), ('ios', 'iOS')], max_length=10)),
                ('rank', models.CharField(blank=True, max_length=4)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('earned_title', models.CharField(blank=True, max_length=100)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('stamina', models.IntegerField(blank=True, null=True)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('guts', models.IntegerField(blank=True, null=True)),
                ('wit', models.IntegerField(blank=True, null=True)),
                ('fans', models.IntegerField(blank=True, null=True)),
                ('races', models.IntegerField(blank=True, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('aptitudes', models.JSONField(blank=True, default=dict)),
                ('major_wins', models.JSONField(blank=True, default=list)),
                ('support_cards', models.JSONField(blank=True, default=list)),
                ('legacy', models.JSONField(blank=True, default=dict)),
                ('source_images', models.JSONField(blank=True, default=list)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='umamusume.outfit')),
            ],
            options={
                'ordering': ['-run_date'],
            },
        ),
        migrations.DeleteModel(
            name='Horse',
        ),
        migrations.AddConstraint(
            model_name='outfit',
            constraint=models.UniqueConstraint(fields=('character', 'title'), name='unique_outfit_per_character'),
        ),
        migrations.AddIndex(
            model_name='careerrun',
            index=models.Index(fields=['-rating'], name='umamusume_c_rating_a48b3b_idx'),
        ),
        migrations.AddIndex(
            model_name='careerrun',
            index=models.Index(fields=['outfit', '-rating'], name='umamusume_c_outfit__bc3ba7_idx'),
        ),
    ]
