# Generated by Django 6.0.1 on 2026-02-08 09:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0002_genre_work_genres_work_primary_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Villager',
            fields=[
                ('id', models.PositiveIntegerField(help_text='ACNH API ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('personality', models.CharField(choices=[('cranky', 'Cranky'), ('jock', 'Jock'), ('lazy', 'Lazy'), ('normal', 'Normal'), ('peppy', 'Peppy'), ('smug', 'Smug'), ('snooty', 'Snooty'), ('uchi', 'Uchi')], max_length=20)),
                ('species', models.CharField(db_index=True, max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('birthday', models.CharField(blank=True, max_length=10)),
                ('catchphrase', models.CharField(blank=True, max_length=100)),
                ('hobby', models.CharField(blank=True, max_length=50)),
                ('saying', models.TextField(blank=True)),
                ('icon_url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('island_name', models.CharField(blank=True, max_length=100)),
                ('player_name', models.CharField(blank=True, max_length=100)),
                ('hemisphere', models.CharField(blank=True, choices=[('north', 'Northern'), ('south', 'Southern')], max_length=10)),
                ('native_fruit', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acnh_profile', to='library.work')),
            ],
        ),
        migrations.CreateModel(
            name='VillagerHunt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunts', to='acnh.profile')),
                ('result_villager', models.ForeignKey(blank=True, help_text='Who you ended up recruiting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hunts_recruited', to='acnh.villager')),
                ('target_villager', models.ForeignKey(blank=True, help_text='Who you were hoping to find', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hunts_targeted', to='acnh.villager')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('bonus_item', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Internal monologue')),
                ('recruited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('villager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='acnh.villager')),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='acnh.villagerhunt')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
