# Generated by Django 6.0.1 on 2026-03-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acnh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='residents',
            field=models.ManyToManyField(blank=True, help_text='Current villagers living on the island', related_name='islands', to='acnh.villager'),
        ),
    ]
