# Generated by Django 6.0.1 on 2026-04-14 07:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0002_genre_work_genres_work_primary_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.CharField(db_index=True, max_length=24, unique=True)),
                ('steam_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('platform', models.CharField(choices=[('pc', 'PC'), ('ps', 'PlayStation'), ('xbox', 'Xbox'), ('switch', 'Switch')], default='pc', max_length=10)),
                ('wf_created_at', models.DateTimeField(blank=True, null=True)),
                ('mastery_rank', models.IntegerField(default=0)),
                ('player_level', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('missions_completed', models.IntegerField(default=0)),
                ('missions_quit', models.IntegerField(default=0)),
                ('missions_failed', models.IntegerField(default=0)),
                ('missions_interrupted', models.IntegerField(default=0)),
                ('missions_dumped', models.IntegerField(default=0)),
                ('time_played_seconds', models.BigIntegerField(default=0)),
                ('pickup_count', models.BigIntegerField(default=0)),
                ('daily_focus', models.IntegerField(default=0)),
                ('migrated_to_console', models.BooleanField(default=False)),
                ('profile_data', models.JSONField(blank=True, default=dict)),
                ('stats_data', models.JSONField(blank=True, default=dict)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warframe_profile', to='library.work')),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('session_end', 'Session End'), ('scheduled', 'Scheduled')], default='manual', max_length=20)),
                ('mastery_rank', models.IntegerField(default=0)),
                ('time_played_seconds', models.BigIntegerField(default=0)),
                ('missions_completed', models.IntegerField(default=0)),
                ('pickup_count', models.BigIntegerField(default=0)),
                ('total_weapon_kills', models.BigIntegerField(default=0)),
                ('weapons_tracked', models.IntegerField(default=0)),
                ('raw_profile', models.JSONField(blank=True, default=dict)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='warframe.profile')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_tag', models.CharField(max_length=50)),
                ('completes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='warframe.profile')),
            ],
            options={
                'ordering': ['-completes'],
                'unique_together': {('profile', 'node_tag')},
            },
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('syndicate_tag', models.CharField(max_length=50)),
                ('standing', models.IntegerField(default=0)),
                ('title_rank', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='warframe.profile')),
            ],
            options={
                'ordering': ['syndicate_tag'],
                'unique_together': {('profile', 'syndicate_tag')},
            },
        ),
        migrations.CreateModel(
            name='WeaponStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weapon_path', models.CharField(max_length=255)),
                ('weapon_name', models.CharField(blank=True, max_length=100)),
                ('fired', models.BigIntegerField(default=0)),
                ('hits', models.BigIntegerField(default=0)),
                ('kills', models.BigIntegerField(default=0)),
                ('headshots', models.BigIntegerField(default=0)),
                ('assists', models.BigIntegerField(default=0)),
                ('equip_time_seconds', models.FloatField(default=0)),
                ('xp', models.BigIntegerField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('headshot_rate', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='warframe.profile')),
            ],
            options={
                'ordering': ['-kills'],
                'indexes': [models.Index(fields=['profile', '-kills'], name='warframe_we_profile_bfa651_idx'), models.Index(fields=['profile', '-equip_time_seconds'], name='warframe_we_profile_9c0887_idx')],
                'unique_together': {('profile', 'weapon_path')},
            },
        ),
    ]
