# Generated by Django 6.0.6 on 2026-06-16 21:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warframe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unique_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('item_type', models.CharField(blank=True, max_length=100)),
                ('mastery_req', models.IntegerField(default=0)),
                ('masterable', models.BooleanField(default=False)),
                ('is_prime', models.BooleanField(default=False)),
                ('image_name', models.CharField(blank=True, max_length=255)),
                ('product_category', models.CharField(blank=True, max_length=100)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
