# Generated by Django 6.0.6 on 2026-06-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warframe', '0002_catalogitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='max_level_cap',
            field=models.IntegerField(default=30),
        ),
    ]
