# Generated by Django 6.0.6 on 2026-06-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warframe', '0003_catalogitem_max_level_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='acquisition',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='vaulted',
            field=models.BooleanField(default=False),
        ),
    ]
