# Generated by Django 6.0.6 on 2026-06-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warframe', '0004_catalogitem_acquisition_catalogitem_vaulted'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='vault_date',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='acquisition',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
