# Generated by Django 6.0.1 on 2026-02-12 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0002_genre_work_genres_work_primary_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.TextField()),
                ('edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ironmon_challenges', to='library.edition')),
            ],
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('trainer', models.TextField()),
                ('order', models.IntegerField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='ironmon.challenge')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('challenge', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('seed_number', models.IntegerField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('is_victory', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ironmon.challenge')),
                ('highest_checkpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ironmon.checkpoint')),
            ],
            options={
                'ordering': ['-seed_number'],
            },
        ),
        migrations.CreateModel(
            name='CheckpointResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleared', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ironmon.checkpoint')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ironmon.run')),
            ],
            options={
                'ordering': ['checkpoint__order'],
                'unique_together': {('run', 'checkpoint')},
            },
        ),
    ]
