# Generated by Django 6.0.1 on 2026-03-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ironmon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpointresult',
            name='cleared',
        ),
    ]
