# Generated by Django 6.0.1 on 2026-03-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironmon', '0002_remove_cleared_from_checkpointresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='defeated_by',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
